version: "3.9"

services:
  backend:
    build: ./face_backend
    container_name: django-backend
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db



  frontend_user:
    build: ./frontend_user
    container_name: react-user-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
