version: "3.9"

services:
  backend:
    build: ./face_backend
    container_name: django-backend

    command: gunicorn face_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./face_backend:/app
      - ./staticfiles:/app/staticfiles
    image: quan23020418/ait_backend:latest

    ports:
      - "8000:8000"
    networks:
      - app-network




  frontend_user:
    build: ./frontend_user
    container_name: react-user-frontend
    image: quan23020418/ait_frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
